# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: AeroRohit
email: rohittembhare1@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

domain: aerorohit.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://aerorohit.github.io  # the base hostname and protocol for your site, e.g. http://example.com


encoding: utf-8 # Make sure the encoding is right
logo: "/assets/logo.svg" # Site logo

# baseurl: "" # the subpath of your site, e.g. /blog
# twitter_username: jekyllrb
# github_username:  aerorohit

# Build settings
plugins:
  - jekyll-feed
  - jekyll-spaceship
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate


# theme: minimal-mistakes-jekyll
# theme: garth-jekyll-theme
# remote_theme: https://github.com/mmistakes/minimal-mistakes
remote_theme: daviddarnes/garth

markdown: kramdown
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


# 3. Gem settings
paginate: 7 # jekyll-paginate > items per page
paginate_path: page:num # jekyll-paginate > blog page

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike


# 5. Collections
collections:
  posts:
    title: Blog # Needed for Siteleaf
    output: true
    # description: "This is merely a demo, find out more" # The post list page content

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
